version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-server
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - jenkins-network
    restart: unless-stopped

  django-app:
    build:
      context: ./django-app
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./simple-django-app:/app
    working_dir: /app/cool_counters
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - jenkins
    networks:
      - jenkins-network
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge
